# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import todo_pb2 as todo__pb2


class TodoStub(object):
  """Todo service definition
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateItem = channel.unary_unary(
        '/todo.Todo/CreateItem',
        request_serializer=todo__pb2.TodoItem.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.UpdateItem = channel.unary_unary(
        '/todo.Todo/UpdateItem',
        request_serializer=todo__pb2.TodoItem.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.GetList = channel.unary_unary(
        '/todo.Todo/GetList',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=todo__pb2.TodoList.FromString,
        )


class TodoServicer(object):
  """Todo service definition
  """

  def CreateItem(self, request, context):
    """Create an item at the end of a todo list
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateItem(self, request, context):
    """Update an item's completeness or order
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetList(self, request, context):
    """Get all the items in a todo list
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateItem': grpc.unary_unary_rpc_method_handler(
          servicer.CreateItem,
          request_deserializer=todo__pb2.TodoItem.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'UpdateItem': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateItem,
          request_deserializer=todo__pb2.TodoItem.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'GetList': grpc.unary_unary_rpc_method_handler(
          servicer.GetList,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=todo__pb2.TodoList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'todo.Todo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
